on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: native
    steps:
    - uses: actions/checkout@v5
    - run: nix build
    - uses: actions/upload-artifact@v4
      with:
        name: nexus_keyboard_overlay
        path: result/lib/*.dll
