on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: native
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Nix
      uses: https://github.com/cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nexus_keyboard_overlay
        path: result/lib/*.dll
